{
 "title": "FastAPI Информативные логи",
 "tags": [
  "fastapi",
  "logs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Количество запросов по методам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method) (count_over_time({container=\"web\", method=~\".+\"} [1m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Ошибки (4xx, 5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status_code) (count_over_time({container=\"web\", status_code=~\"4..\"} [1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum by (status_code) (count_over_time({container=\"web\", status_code=~\"5..\"} [1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Топ-5 эндпоинтов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, sum by (url) (count_over_time({container=\"web\", url=~\".+\"} [1m])))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Количество запросов по статус-кодам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status_code) (count_over_time({container=\"web\", status_code=~\".+\"} [1m]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Общее количество запросов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"web\", status_code=~\".+\"} [1m]))",
     "legendFormat": "Запросы"
    }
   ]
  },
  {
   "title": "Детальные логи",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container=\"web\"}"
    }
   ]
  }
 ]
}