server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ['web', 'web2']
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: timestamp
            name: name
            container: container
            status_code: status_code
            url: url
            method: method
            client: client
            error: error
            duration: duration
            service_name: service_name
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05,000"
      - labels:
          level:
          container:
          name:
          status_code:
          url:
          method:
          client:
          error:
          service_name:
      - metrics:
          duration:
            type: Histogram
            description: "Request duration in seconds"
            source: duration
            config:
              buckets: [0.1, 0.5, 1, 2, 5] 